import { type NextPage } from "next";
import Head from "next/head";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data } = api.labor_stats.getEmploymentByGeography.useQuery({
    geography: "Canada ",
    typeOfEmployee: "Salaried employees paid a fixed salary",
  });

  const chartData = [
    {
      dataKey: "forestry_logging_and_support",
      fill: "#3AB795",
      name: "Forestry",
    },
    {
      dataKey: "mining_quarrying_and_oil_and_gas_extraction",
      fill: "#A0E8AF",
      name: "Mining",
    },
    { dataKey: "utilities", fill: "#86BAA1", name: "Utilities" },
    { dataKey: "construction", fill: "#EDEAD0", name: "Construction" },
    { dataKey: "manufacturing", fill: "#FFCF56", name: "Manufacturing" },
  ];

  const Chart = () => {
    return (
      <ResponsiveContainer width={700} height={300}>
        <AreaChart
          data={data}
          margin={{
            top: 10,
            right: 0,
            left: 70,
            bottom: 0,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="month" />
          <YAxis
            tickFormatter={(value) =>
              new Intl.NumberFormat("en-US", {
                notation: "compact",
                compactDisplay: "short",
              }).format(value)
            }
          />
          <Tooltip
            formatter={(value) => value && value.toLocaleString()}
            wrapperStyle={{ outline: "none" }}
          />
          {chartData.map((item) => {
            return (
              <Area
                type="monotone"
                name={item.name}
                dataKey={item.dataKey}
                stroke={item.fill}
                fill={item.fill}
                stackId="1"
              />
            );
          })}
        </AreaChart>
      </ResponsiveContainer>
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div>Hi there</div>
        <div className="w-full">{data && <Chart />}</div>
        {/* </div> */}
      </main>
    </>
  );
};

export default Home;
