import { type NextPage } from "next";
import Head from "next/head";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

import { api } from "../utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = api.labor_stats.getEmploymentByGeography.useQuery({
    geography: "Canada ",
    typeOfEmployee: "Salaried employees paid a fixed salary",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "> */}
        Hi there
        <LineChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 5,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          {/* <Legend /> */}
          <Line
            type="monotone"
            dataKey="forestry_logging_and_support"
            stroke="#8884d8"
            activeDot={{ r: 8 }}
          />
          <Line
            type="monotone"
            dataKey="mining_quarrying_and_oil_and_gas_extraction"
            stroke="#82ca9d"
          />
          <Line type="monotone" dataKey="utilities" stroke="red" />
          <Line type="monotone" dataKey="construction" stroke="blue" />
          <Line type="monotone" dataKey="manufacturing" stroke="green" />
        </LineChart>
        {/* </div> */}
      </main>
    </>
  );
};

export default Home;
